"""Shared component scaffolding for all four styles."""
import math, html
from svgkit import Doc, face, svg, minify
import content as C

W = 848            # README content width on the profile page
CARD_W, CARD_H = 412, 140
STAT_W, STAT_H = 495, 195   # same aspect as streak-stats so pairs line up


def esc(s):
    return html.escape(s, quote=True)


def wrap(f, text, size, max_w, tracking=0):
    words = text.split(" ")
    lines, cur = [], ""
    for w in words:
        t = (cur + " " + w).strip()
        if f.measure(t, size, tracking) <= max_w or not cur:
            cur = t
        else:
            lines.append(cur); cur = w
    if cur:
        lines.append(cur)
    return lines


def rr(x, y, w, h, r=0, fill="none", stroke="none", sw=1, extra=""):
    return f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="{r}" fill="{fill}" stroke="{stroke}" stroke-width="{sw}" {extra}/>'


def line(x1, y1, x2, y2, stroke, sw=1, extra=""):
    return f'<line x1="{x1}" y1="{y1}" x2="{x2}" y2="{y2}" stroke="{stroke}" stroke-width="{sw}" {extra}/>'


def star(cx, cy, r, fill, points=5, inner=0.45, extra=""):
    pts = []
    for i in range(points * 2):
        a = -math.pi / 2 + i * math.pi / points
        rad = r if i % 2 == 0 else r * inner
        pts.append(f"{cx + rad*math.cos(a):.2f},{cy + rad*math.sin(a):.2f}")
    return f'<polygon points="{" ".join(pts)}" fill="{fill}" {extra}/>'


class Style:
    id = "base"
    name = "Base"
    pal = {}
    # page background GitHub uses in dark mode — assets sit on this
    page_bg = "#0d1117"

    def __init__(self):
        self.assets = {}   # filename -> svg string

    # ---- fonts (override) ----
    def fonts(self):
        raise NotImplementedError

    # ---- helpers ----
    def T(self, doc, f, txt, x, y, size, fill, **kw):
        m, w = doc.text(f, txt, x, y, size, fill=fill, **kw)
        return m

    def TW(self, doc, f, txt, x, y, size, fill, **kw):
        return doc.text(f, txt, x, y, size, fill=fill, **kw)

    def out(self, name, s):
        self.assets[name] = minify(s)

    # ---- components every style must provide ----
    def hero(self): raise NotImplementedError
    def section(self, idx, title): raise NotImplementedError
    def card(self, idx, project): raise NotImplementedError
    def wins(self): raise NotImplementedError
    def stack(self): return None          # None -> README uses a native/3rd-party block
    def stats_card(self, data=None): raise NotImplementedError
    def langs_card(self, langs=None): raise NotImplementedError
    def activity_card(self, vals=None): raise NotImplementedError
    def button(self, kind, label): raise NotImplementedError
    def footer(self): raise NotImplementedError

    # ---- third-party widget theming ----
    def typing_url(self): raise NotImplementedError
    def streak_url(self): raise NotImplementedError
    def snake_css(self): raise NotImplementedError

    # ---- README pieces (markdown) ----
    def md_about(self): raise NotImplementedError
    def md_stack(self): raise NotImplementedError

    def build(self):
        self.out("hero.svg", self.hero())
        for i, t in enumerate(["about", "featured", "wins", "stack", "stats", "contact"], 1):
            self.out(f"sec-{t}.svg", self.section(i, t))
        for i, p in enumerate(C.PROJECTS, 1):
            self.out(f"card-{i}.svg", self.card(i, p))
        self.out("wins.svg", self.wins())
        st = self.stack()
        if st:
            self.out("stack.svg", st)
        self.out("stats.svg", self.stats_card())
        self.out("langs.svg", self.langs_card())
        self.out("activity.svg", self.activity_card())
        for k, l in [("email", "Email"), ("linkedin", "LinkedIn"), ("resume", "Resume")]:
            self.out(f"btn-{k}.svg", self.button(k, l))
        self.out("footer.svg", self.footer())
        return self.assets

    def readme(self, asset_prefix="assets"):
        a = lambda n: f"{asset_prefix}/{n}"
        P = C.PROJECTS
        def card_link(i, p):
            url = p[1] or "#"
            todo = "" if p[1] else f'  <!-- TODO(sagar): replace href="#" below with the {p[0]} repo URL -->\n'
            return f'{todo}  <a href="{url}"><img src="{a(f"card-{i}.svg")}" width="49%" alt="{esc(p[0])}"></a>'
        cards = "\n".join(
            f'<p align="center">\n{card_link(i, P[i-1])}\n{card_link(i+1, P[i])}\n</p>'
            for i in (1, 3))
        snake = (f"https://raw.githubusercontent.com/{C.HANDLE}/{C.HANDLE}/output/github-contribution-grid-snake-dark.svg")
        md = f"""<!-- Generated by .github/scripts/build.py — edit content.py and re-run, or edit this file directly (assets stay the same). -->
<p align="center">
  <img src="{a('hero.svg')}" width="100%" alt="{C.NAME} — {esc(C.TAGLINE)}">
</p>
<p align="center">
  <img src="{self.typing_url()}" alt="{esc(' · '.join(C.TYPING_LINES))}">
</p>

<img src="{a('sec-about.svg')}" width="100%" alt="About">

{self.md_about()}

<img src="{a('sec-featured.svg')}" width="100%" alt="Featured work">

{cards}

<img src="{a('sec-wins.svg')}" width="100%" alt="Wins">

<p align="center"><img src="{a('wins.svg')}" width="100%" alt="{esc(' · '.join(w[0] + ' ' + w[1] for w in C.WINS))}"></p>

<img src="{a('sec-stack.svg')}" width="100%" alt="Stack">

{self.md_stack(a)}

<img src="{a('sec-stats.svg')}" width="100%" alt="Stats">

<p align="center">
  <img src="{a('stats.svg')}" width="49%" alt="GitHub stats">
  <!-- streak card is live from streak-stats.demolab.com — delete the next line to hide it -->
  <img src="{self.streak_url()}" width="49%" alt="Contribution streak">
</p>
<p align="center">
  <img src="{a('langs.svg')}" width="49%" alt="Top languages">
  <img src="{a('activity.svg')}" width="49%" alt="Contribution activity">
</p>
<p align="center">
  <img src="{snake}" width="100%" alt="Contribution snake">
</p>

<img src="{a('sec-contact.svg')}" width="100%" alt="Contact">

<p align="center">
  <a href="mailto:{C.EMAIL}"><img src="{a('btn-email.svg')}" height="42" alt="Email"></a>
  <a href="{C.LINKEDIN}"><img src="{a('btn-linkedin.svg')}" height="42" alt="LinkedIn"></a>
  <!-- TODO(sagar): commit resume.pdf next to this README, or change the href below to a Drive / website link -->
  <a href="{C.RESUME}"><img src="{a('btn-resume.svg')}" height="42" alt="Resume"></a>
</p>

<p align="center"><img src="{a('footer.svg')}" width="100%" alt="© 2026 {C.NAME}"></p>
"""
        return md


def sample_activity(n=52, seed=7):
    import random
    r = random.Random(seed)
    vals, v = [], 2
    for i in range(n):
        v = max(0, min(14, v + r.randint(-3, 4)))
        vals.append(v)
    return vals
